import { WINE1 } from "../assets/images";

export const COLLECTION_CARD = [
  {
    id: 1,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 2,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 3,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 4,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "99 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
];
